### ISSUE TITLE
#createServer params

### ISSUE THREAD

**Issue by revington** [ekristen/prometheus-client#1]
Here https://github.com/ekristen/prometheus-client/blob/master/lib/client.js#L79 the create server function accepts the `listen` parameter. 
On the documentation, create server is called with a port 
```
client.createServer(9090)
```
But that port will not be used. Right?

**Comment by ekristen** [comment]
Originally it was built like the documentation states, but ultimately that didn't work for my uses, so I built a second method, if you don't pass in a port, it'll use the port passed in to the client when you instantiate it.

**Comment by revington** [comment]
The original http server node includes will find an available port when no port is supplied. [Supertest](https://github.com/visionmedia/supertest) among  others relies on this behavior in order to expose the following:
```
var request = require('supertest');
function app(req, res){ res.send('hello')}
request(app).get('/')...
```
For any piece of code like the later it will be easy to resolve the port
```
function something(app){
  var server = http.createServer(app);
  server.listen(function(){
    console.log(server.address().port);
  });
}
```
Because of the default port it is more difficult to perform integration tests on my own code. I need to find free ports during the integration test.
Will you accept a PR were the server creation behaves as the original http server?
